server:
  tomcat:
    accept-count: 1000  #当所有可能的请求处理线程都在使用时，传入连接请求的最大队列长度
    connection-timeout: 20000 #连接超时时间
    min-spare-threads: 20  #最小工作线程数
    max-threads: 1000  #最大工作线程数
    uri-encoding: UTF-8
  port: 20100
  max-http-header-size: 20480
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - text/html
    - text/xml
    - text/javascript
    - text/css
    - text/plain
  servlet:
    context-path: /vmi-video-service
    session:
      timeout: 7200
      cookie:
        name: JSESSION
        path: /
        http-only: true
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.20.3:3306/vmi_production?serverTimezone=GMT%2B8&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&connectTimeout=5000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: vmi
    password: c9T2Dx03
    maxActive: 50
    minIdle: 10
    initialSize: 10
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 180000
    connectionProperties: 
    validationQuery: select 1
    connectionInitSqls: set names utf8mb4;
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
    slowSqlMillis: 1000
    mergeSql: true
  redis:
    host: 192.168.20.84
    port: 6379
    db: 3
    timeout: 2000
    active: 64
    idle: 4
    waitMillis: 1000
    borrowCheck: true
    returnCheck: false
    password:
  storage:
    minio:
      endpoint: http://192.168.20.30:9000
      bucketname: yoyo
      username: 6DZNVXPPU4E8AF4ES61W
      password: HpVCTLJDjk1fpJV24WVbJWrthO1TktzELhGKFk4j
    upaiyun:
      bucketname: yoyo-test-new
      username: yoyotest
      password: 4wbHqZgX69qBJ3KE1xub9nc8GfJs2UUG
  search:
    elastic:
      host: 192.168.20.17
      port: 9200
      user: elastic
      password: Annal7-Astride
      schema: http
      connectTimeOut: 5000
      socketTimeOut: 30000
      connectionRequestTimeOut: 500
      maxConnectNum: 100
      maxConnectPerRoute: 100
#日志
logging:
  config: classpath:logback-spring.xml
  file:
    path: /opt/backend/vmi-video-service/logs
  level:
    java.sql.Connection: DEBUG
    java.sql.Statement: DEBUG
    java.sql.PreparedStatement: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
        